"""Add canonical system user for hash-chain audit trail.

The hash payload includes created_by. When entries are generated by automated
processes (purchase posting, depreciation, period closing), created_by was NULL
which serialised as the string "None" — technically consistent but useless for
forensic audit because no real user is identified.

This migration inserts a well-known system sentinel user so automated entries
have a traceable, stable identity in the audit chain without requiring a FK.

revision: 013_add_system_user
"""
from alembic import op

revision = "013_add_system_user"
down_revision = "012_nullable_journal_created_by"
branch_labels = None
depends_on = None

SYSTEM_USER_ID   = "00000000-0000-0000-0000-000000000000"
SYSTEM_TENANT_ID = "00000000-0000-0000-0000-000000000001"


def upgrade():
    op.execute(f"""
        INSERT INTO users (id, tenant_id, email, password_hash, role, is_active, created_at)
        VALUES (
            '{SYSTEM_USER_ID}',
            '{SYSTEM_TENANT_ID}',
            'sistema@contapro.internal',
            NULL,
            'SYSTEM',
            false,
            NOW()
        )
        ON CONFLICT (id) DO NOTHING
    """)


def downgrade():
    op.execute(f"DELETE FROM users WHERE id = '{SYSTEM_USER_ID}'")
